version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_vector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter_notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - app_network

  document_processor:
    build: ./document_processor
    container_name: doc_processor
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./documents:/app/documents
      - ./logs:/app/logs
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  chatbot:
    build: ./chatbot
    container_name: chatbot
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8501:8501" # Changed to expose Streamlit's default port 8501
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"] # Updated health check for port 8501 (Streamlit UI)
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
